### ISSUE TITLE
Confirm basic CLI usage

### ISSUE THREAD

**Issue by travispaul** [benjojo/userspace-vga2usb#1]
I have one of the VGA2USB devices and was looking for an alternative to running a Windows VM. I came across this project and was hoping to get it working with my device.

My device has a slightly difference Product ID of ``1110`` and [changing this in the code](https://github.com/benjojo/userspace-vga2usb/blob/master/driver/main.go#L36) got me past my initial hurdle (unable to find device) but I might have some more work ahead of me to grab a frame.

I was hoping you could confirm the minimal commands that need to be ran so I can first determine if I'm just doing something incorrectly.

Based on the hints on you your blogpost:

> So now we know this device well enough to explain how to operate it from a cold boot:
> 
> 1. You need to initialise the USB controller. I assume based on the size of information, this is actually uploading code to the USB controller

I assume this would be: ``./bin/driver -stage1``? 

This appears to succeed for me with:

```
2020/07/12 10:34:22 Opening device...
2020/07/12 10:34:22 Claim default interface...
	INTERFACE #0
		0 - Number: 0 - Alt 0
			130 - gousb.EndpointDesc{Address:0x82, Number:2, Direction:true, MaxPacketSize:512, TransferType:0x2, PollInterval:0, IsoSyncType:0x0, UsageType:0x0}
2020/07/12 10:34:22 Setting the USB Controller firmware
UUUUUUUUSSSSSSSSBBBBBBBB2020/07/12 10:34:22 Set the USB Controller firmware
```

> 2. When you’ve done the USB upload, the device will disconnect from the USB bus, and come back a moment later, with only a single USB endpoint.

Not sure if I should expect anything to happen for this step or if there is anything I could check to confirm.

> 3. You can then start sending the FPGA bitstream, one 64 byte USB control packet at a time.

I assume this would be: ``./bin/driver -stage2``? 

This just hangs, if I'm on the right track perhaps my product ID has a different FPGA bitstream. However, this is the debug output I get:

```
2020/07/12 10:34:25 Opening device...
2020/07/12 10:34:25 Claim default interface...
	INTERFACE #0
		0 - Number: 0 - Alt 0
			130 - gousb.EndpointDesc{Address:0x82, Number:2, Direction:true, MaxPacketSize:512, TransferType:0x2, PollInterval:0, IsoSyncType:0x0, UsageType:0x0}
2020/07/12 10:34:26 Setting the FPGA bitstream I think...
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

> 4. Once you are finished, the LED on the device will start blinking green. At this point you can send what appears to be a parameter sequence (overscan and other properties)

This doesn't happen in my case.

> 5. You can then fire a single control packet to get a frame, the control packet has the resolution embedded in it. If you use a 4:3 request packet on a widescreen input you will often end up with a corrupted input.

I assume this would be then: ``./bin/driver -mjpeg``? I get:
```
2020/07/12 10:34:55 Opening device...
2020/07/12 10:34:55 Claim default interface...
	INTERFACE #0
		0 - Number: 0 - Alt 0
			130 - gousb.EndpointDesc{Address:0x82, Number:2, Direction:true, MaxPacketSize:512, TransferType:0x2, PollInterval:0, IsoSyncType:0x0, UsageType:0x0}
2020/07/12 10:34:55 Set a -stage1 or -stage2
```

> To make use as easy as possible, I ended up rigging up a small web server inside the driver to make it super easy to use in a rush.

I assume that the web interface only works after running stage1 and stage2?

```
2020/07/12 10:34:47 Opening device...
2020/07/12 10:34:47 Claim default interface...
	INTERFACE #0
		0 - Number: 0 - Alt 0
			130 - gousb.EndpointDesc{Address:0x82, Number:2, Direction:true, MaxPacketSize:512, TransferType:0x2, PollInterval:0, IsoSyncType:0x0, UsageType:0x0}
2020/07/12 10:34:47 Set a -stage1 or -stage2
```

Thanks in advance for any advice or hints you could share!

**Comment by benjojo** [comment]
What colour is your device? Is it orange?

**Comment by travispaul** [comment]
It is red and I am just now noticing that it does not have "LR" in the name. There are more differences between these devices than I originally thought.

**Comment by benjojo** [comment]
I suspect the Red one _might_ need a different bitstream. If you feel like replicating the [original blog post](https://blog.benjojo.co.uk/post/userspace-usb-drivers) we can add support for this (Just provide USB pcaps I guess)

**Comment by benjojo** [comment]
Poke me if you end up getting pcaps ;) and I'll re-open

**Comment by travispaul** [comment]
Will do, just need some spare time to get that setup and pcap'd, thanks for the help thus far (I will be back!) :)
